# Generated by Django 4.2.1 on 2023-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.IntegerField(blank=True),
        ),
    ]
