# Generated by Django 4.2.1 on 2023-06-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demostaticapp', '0003_alter_team_timg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='timg',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
